### ISSUE TITLE
Image not rendering for forums.rocket.chat

### ISSUE THREAD

**Issue by SiddheshKukade** [RocketChat/developer-docs#152] opened 2023-01-26 12:18 UTC
# Prerequisites

Please answer the following questions before opening an issue.

- [x] I checked to make sure that this issue has not already been filed
- [x] This issue concerns the developer's docs

## Existing Docs

In the page the logo for `forums.rocket.chat` is missing.

![image](https://user-images.githubusercontent.com/65951872/214832679-c1583bf4-5abe-4616-bba6-ed7ab8e86aa9.png)

### Expected Behavior

The logo must be added to `forums.rocket.chat` to make it look consistent.

![image](https://user-images.githubusercontent.com/65951872/214832951-edb9d2d1-49c1-4e33-9f31-cf5685bccf3a.png)

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Go to https://developer.rocket.chat/rocket.chat/contribute-to-rocket.chat 
2. scroll down
3. you can see the missing logo on `forums.rocket.chat`

### Details
![image](https://user-images.githubusercontent.com/65951872/214833013-14af9c5b-cbce-4c7c-a79c-e439b4c97284.png)

Please provide your details and description here.
I would like to work on this issue if that is valid. Please assign this issue to @SiddheshKukade, Thanks.

**Comment by SiddheshKukade** [comment] 2023-01-26 12:20
@Faria-TechWrite, Hello mam, do I have to wait until this issue is assigned to me or can I start working on it rightaway.

**Comment by Faria-TechWrite** [comment] 2023-01-26 13:00
Hi Siddhesh! The issue is assigned to you now.

**Comment by SiddheshKukade** [comment] 2023-01-26 17:52
Hello, @Faria-TechWrite I tried installing `gitbook-cli` with node v16 and it started giving errors for `gitbook serve`  and I downgraded to node v10 and then it started giving some markdown support errors. 
Can you tell how do you guys setup this project for development? or which nodeJS version do you use to set this up? 
That would be very helpful. Thanks.

**Comment by SiddheshKukade** [comment] 2023-01-27 10:59
@Faria-TechWrite It would also be great If you can link a guide for the setup of this project. Actually, I couldn't find it.

**Comment by Rodriq** [comment] 2023-03-13 19:27
Hello, @SiddheshKukade Thank you for pointing this out.
The image is automatically picked up by Gitbook.
As for now, we've updated the structure of that page and it's now using link ref.
For this reason, I am going to close this issue.

See a guide here on how to contribute to the docs: https://docs.rocket.chat/contribute-to-rocket.chat/how-can-i-help/documentation
Gitbook doesn't support CLI anymore. You need to create a space nd import the forked repo or do changes in Markdown.

**Closed by Rodriq** 2023-03-13 19:27 UTC
